# /**:
#   ros__parameters:
#     use_sim_time: true

# /$(var namespace)/controller_manager:
#   ros__parameters:
#     use_sim_time: true
#     update_rate: 1000

#     diff_drive_controller:
#       type: diff_drive_controller/DiffDriveController
    
#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster

# /$(var namespace)/diff_drive_controller:
#   ros__parameters:
#     type: diff_drive_controller/DiffDriveController
#     use_sim_time: true
#     publish_rate: 62.0

#     use_stamped_vel: false
#     enable_odom_tf: true
#     publish_limited_velocity: true 

#     # Robot model
#     base_frame_id: $(var namespace)/base_link
#     left_wheel_names: ['left_wheel_joint']
#     right_wheel_names: ['right_wheel_joint']
#     wheel_separation: 0.233
#     wheel_radius: 0.03575

#     # Velocity and acceleration limits
#     linear:
#       x:
#         has_velocity_limits: true
#         has_acceleration_limits: true
#         max_velocity: 3.0
#         max_acceleration: 3.0
      
#     angular:
#       z:
#         has_velocity_limits: true
#         has_acceleration_limits: true
#         max_velocity: 2.0
#         max_acceleration: 5.0





# /robot1/controller_manager:
/**/controller_manager:
  ros__parameters:

    use_sim_time: true # This will be set to false on real robot in launch file

    update_rate: 1000

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# /robot1/diff_drive_controller:
/**/diff_drive_controller:
  ros__parameters:

    type: diff_drive_controller/DiffDriveController

    use_sim_time: true # This will be set to false on real robot in launch file

    publish_rate: 62.0 # You can set this higher than the controller manager update rate, but it will be throttled

    use_stamped_vel: false # Depending on if cmd_vel is presented as Twist or TwistStamped:
    enable_odom_tf: true
    publish_limited_velocity: true 

    # Robot model
    odom_frame_id: odom

    base_frame_id: base_link
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.233
    wheel_radius: 0.03575

    # Velocity and acceleration limits of robot
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 3.0
        max_acceleration: 3.0
      
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 2.0
        max_acceleration: 5.0














# controller_manager:
#   ros__parameters:
#     update_rate: 1000  # Hz

#     joint_state_broadcaster:
#       type: joint_state_broadcaster/JointStateBroadcaster
    
#     diff_drive_base_controller:
#       type: diff_drive_controller/DiffDriveController


# diff_drive_base_controller:
#   ros__parameters:
#     left_wheel_names: ["left_wheel_joint"]
#     right_wheel_names: ["right_wheel_joint"]

#     wheel_separation: 0.233
#     wheel_radius: 0.03575

#     wheel_separation_multiplier: 1.0
#     left_wheel_radius_multiplier: 1.0
#     right_wheel_radius_multiplier: 1.0

#     publish_rate: 50.0
#     odom_frame_id: odom
#     base_frame_id: chassis
#     pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
#     twist_covariance_diagonal: [0.001, 0.0, 0.0, 0.0, 0.0, 0.01]

#     open_loop: true
#     enable_odom_tf: true

#     cmd_vel_timeout: 0.5
#     #publish_limited_velocity: true
#     #velocity_rolling_window_size: 10

#     # Velocity and acceleration limits
#     # Whenever a min_* is unspecified, default to -max_*
#     linear.x.has_velocity_limits: true
#     linear.x.has_acceleration_limits: true
#     linear.x.has_jerk_limits: false
#     linear.x.max_velocity: 1.0
#     linear.x.min_velocity: -1.0
#     linear.x.max_acceleration: 1.0
#     linear.x.max_jerk: 0.0
#     linear.x.min_jerk: 0.0

#     angular.z.has_velocity_limits: true
#     angular.z.has_acceleration_limits: true
#     angular.z.has_jerk_limits: false
#     angular.z.max_velocity: 1.0
#     angular.z.min_velocity: -1.0
#     angular.z.max_acceleration: 1.0
#     angular.z.min_acceleration: -1.0
#     angular.z.max_jerk: 0.0
#     angular.z.min_jerk: 0.0
